# Generated by Django 4.0.1 on 2022-01-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airplane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('passanger', models.IntegerField()),
            ],
        ),
    ]
