# Generated by Django 4.0.1 on 2022-01-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplane',
            old_name='passanger',
            new_name='passenger',
        ),
    ]
