# Generated by Django 4.0.1 on 2022-01-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_passanger_airplane_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='passenger',
            field=models.PositiveIntegerField(),
        ),
    ]
